---
sidebar: sidebar
permalink: finding-compatible-with-hba-cards.html
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified Solutions, workflow, compatible, hba, cards
summary:  'You can use Interoperability Matrix Tool to view the supported host operating system for a configuration like Cisco UCS P81E card on FCoE.'
---
= Find compatibility with HBA cards
:icons: font
:imagesdir: ./media/

[.lead]
With ONTAP SAN Host Simplified solution, the UI has been simplified to three components, compared to 13 earlier. Remaining ten components are implicitly supported by NetApp, provided they are supported by the respective vendors. Notes and Alerts are categorized solution wise and added to each result.

The three components supported in IMT are ONTAP, Host OS and Protocol. 

You can use Interoperability Matrix Tool to view the supported host operating systems support with ONTAP.

For example, to validate a Cisco UCS Blade server supportability with ONTAP, a sample configuration would be as follows:

*Example sample configuration*

* ONTAP: 9.13.1
* Host OS: Red Hat Enterprise Linux 9.2
* Server model: Cisco UCS B200 M6 Blade server
* HBA adapter
** Model: Cisco UCSB-MLOM-40G-04: Cisco UCS 1440 Virtual Interface Card
** Driver version: 1.6.0.53 fnic 
** firmware version: 5.3(2)
* UCS Server Firmware: 5.2(0)
* Protocol: FCoE

You can use the following procedure to verify compatibility with Host Bus adapters (HBAs).

.Steps

. Check the IMT ONTAP SAN Host Simplified solution to validate ONTAP 9.13.1, Red Hat Enterprise Linux 9.2 and FCoE protocol is listed as supported
. Since Cisco is one among the supported adapter list, Cisco VIC is supported as well. The HBA vendors supported by NetApp are Broadcom, Marvell and Cisco
. Check Cisco "UCS Hardware and Software Compatibility" aka HCL to validate this configuration is listed as supported.

