---
sidebar: sidebar
permalink: finding-compatible-with-hba-cards.html
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, workflow, compatible, hba, cards
summary:  'You can use Interoperability Matrix Tool to view the supported host operating system for a configuration like Cisco UCS P81E card on FCoE.'
---
= Find compatibility with HBA cards
:icons: font
:imagesdir: ./media/

[.lead]
With the *ONTAP SAN Host Simplified* feature, the UI is simplified and condensed into three components; there were thirteen components in earlier versions of the UI. The remaining ten components are implicitly supported by NetApp, provided they are supported by the respective vendors. *Notes* and *Alerts* are categorized by solutions and are added to each result.

The three components supported in Interoperability Matrix Tool (IMT) are ONTAP OS, Host OS, and Protocol. 

You can use IMT to validate the host OS supportability with ONTAP. 

For example, validate Cisco Unified Computing System (Cisco UCS) Blade server supportability with ONTAP using the following configuration:

*Example Cisco UCS Blade server configuration* 

* ONTAP OS: 9.13.1
* Host OS: Red Hat Enterprise Linux 9.2
* Server model: Cisco UCS B200 M6 Blade server
* Host bus adapter (HBA) 
** Model: Cisco UCSB-MLOM-40G-04: Cisco UCS 1440 Virtual Interface Card
** Driver version: 1.6.0.53 fnic 
** Firmware version: 5.3(2)
* UCS Server Firmware: 5.2(0)
* Protocol: FCoE

*Validate Cisco UCS Blade server supportability*

* Use the *ONTAP SAN Host Simplified* feature in IMT to verify ONTAP 9.13.1, Red Hat Enterprise Linux 9.2, and FCoE protocol are listed as supported configurations.

* The HBA vendors supported by NetApp are Broadcom, Marvell, and Cisco. Cisco is included in the supported adapter list which implies the Cisco Virtual Interface Card (VIC) is also supported. 

* Use the vendor Hardware Compatibility list (HCL) to verify Cisco "UCS Hardware and Software Compatibility". As mentioned in the preceding list, verify the HBA adapter model, the UCS server firmware version, and the HBA driver and firmware versions are supported with Red Hat Enterprise Linux 9.2. 


//29-Sep-2023 OTHERDOC-31