---
sidebar: sidebar
permalink: finding-compatible-with-hba-cards.html
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified Solutions, workflow, compatible, hba, cards
summary:  'You can use Interoperability Matrix Tool to view the supported host operating system for a configuration like Cisco UCS P81E card on FCoE.'
---
= Find compatibility with HBA cards
:icons: font
:imagesdir: ./media/

[.lead]
With the *ONTAP SAN Host Simplified Solution* search, the UI has been simplified to three components as compared to thirteen components present in the earlier versions. The remaining ten components are implicitly supported by NetApp, provided they are supported by the respective vendors. *Notes* and *Alerts* are categorized by solutions and are added to each result.

The three components supported in Interoperability Matrix Tool (IMT) are ONTAP, Host OS, and Protocol. 

You can use IMT to view the host OS supportability with ONTAP. For example, to validate a Cisco UCS Blade server supportability with ONTAP, a sample configuration will be as follows:

*Example* 

*Sample configuration*

* ONTAP: 9.13.1
* Host OS: Red Hat Enterprise Linux 9.2
* Server model: Cisco UCS B200 M6 Blade server
* HBA adapter
** Model: Cisco UCSB-MLOM-40G-04: Cisco UCS 1440 Virtual Interface Card
** Driver version: 1.6.0.53 fnic 
** Firmware version: 5.3(2)
* UCS Server Firmware: 5.2(0)
* Protocol: FCoE

*Validate the sample configuration*

* Verify in IMT using the *SAN Host Simplified Solution* search to validate ONTAP 9.13.1, Red Hat Enterprise Linux 9.2, and FCoE protocol are listed as supported.
+
The HBA vendors supported by NetApp are Broadcom, Marvell, and Cisco. Because Cisco is one among the supported adapter list, Cisco Virtual Interface Card is supported as well. 

* Verify Cisco "UCS Hardware and Software Compatibility" aka HCL to validate this configuration is listed as supported.

You can use the procedure to access *ONTAP SAN Host Simplified Solution* on IMT using a web browser on your computer.

.Steps

. Choose a web browser (Safari, Mozilla Firefox, or Google Chrome).
. Open the IMT webpage link:https://imt.netapp.com/matrix/#welcome
. Select the "Solution Search" tile.
. Search for "Simplified" and select the solution and add it.
. Search for the required component and apply the appropriate filters to view the results.
. View the desired configuration supportability details on the results page.


//29-Sep-2023 OTHERDOC-31