---
sidebar: _sidebar
permalink: interoperability-matrix-tool-overview.html
keywords: cable,..
summary:  Determine ..
---


= Performing common searches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/



[.lead]
Use the cards on the home page of the Interoperability Matrix Tool (IMT) to perform common searches, including the ONTAP SAN Host Solutions, Solution Search, List and Find, and Advanced Search.

When you open the IMT, you see the most common search types on the home page:

* ONTAP SAN Host Solutions
* Solution Search
* List and Find
* Advanced Search

You can also watch training videos or open the Active IQ Advisor from the home page.

== Working with ONTAP SAN Host Solutions search
Check compatibility for ONTAP version and Flash or Fabric storage version combinations. You can further refine your compatibility search for each relevant components.

=== About this task
You can quickly check the compatibility between your Flash or Fabric storage devices on your storage area network (SAN) with the ONTAP version you want to use and other relevant
components. You can choose between Expert view or Novice
view.


NOTE: Click *Set as default* to automatically open a ONTAP SAN Host Solutions search
whenever you open the IMT.

=== Steps
1. Click *ONTAP SAN Host Solutions* from the home page.
2. Select the view you want to use:
a. Click *Expert view* to see advanced criteria options.
b. Click *Guided view* to see simplified and guided criteria options.
3. In *Novice view*, select the search criteria options as they display.
a. Click *Skip* to move to the next component without making a selection. You can return to
the component by clicking *Unskip* as needed.
b. After the first five selections, click *Show More* to continue refining your search criteria.
c. When done, click View Results to see the supported configurations for your search criteria.
4. In *Expert view*, select the search criteria you want to use for the various components. We
recommend you move from left to right as each selection will refine the remaining criteria. You
do not have to make a selection for each component.
a. When done, click *View Results* to see the supported configurations for your search criteria.
5. You can also do the following as part of the ONTAP SAN Host Solutions:
a. Click the book icon to view the policy and guidelines applicable to your selection.
b. Click the chain icon to generate a sharable URL for your selections that you can share with
others.
c. Select the undo icon to clear all of you selections and start again.
6. From the results screen, you can do the following:
a. View the details, alerts, and information notices about your configuration.
b. Click the star icon to make this search a favorite. Name and describe the configuration. This
becomes a saved search, viewable from the *Saved Search* menu. You can also subscribe to
the configuration here, which will notify you when changes are made. If you subscribe, you
will also see this listed under the *Subscriptions* menu.
c. Hover over the *Build End to End View With* to find additional supported solutions.
d. Click *What if* to change components and explore other compatibility options.

== Working with Solution Search
You can search for different storage solutions, and add or remove solutions from your search criteria. You can use the search text box within the Solution Search page to search for a specific solution. Frequently accessed solutions are displayed in the Solution Search field.

=== About this task
The *Solution Search* page includes a *Solution Catalog* tab and a *Mapping Assistant* tab. In the *Mapping Assistant* tab, you can see the category of a selected solution by selecting either *Map by Category* or *Map by Solution*.

==== Solution Catalog
On the *Solution Catalog* tab, you can *Filter Solutions* using the filter bar.

You can also select the *Include PVR Required, EOS, and Obsolete configurations* if you want to include such configurations.

==== Mapping Assistant
The following are the two types of work area modes:

* *Map by Category*: You can select a category from the listed categories, and to enable all of the solutions containing the selected category, with valid solutions at the top of the list. You can add single or multiple enabled solutions of your choice. You can use the *Search Categories* text box to search for a specific category.
* *Map by Solution*: You can select a solution from the listed solutions, and to enable all of the solutions containing the selected solution, with valid solutions at the top of the list. You can add single or multiple enabled solutions of your choice. You can use the *Search Solutions* text box to search for a specific category.

You can also select the *Include PVR Required, EOS, and Obsolete configurations* if you want to include such configurations.

When done, you can see the items you have selected under the *Selected Storage Solutions*. *Click View Refine Search Criteria* or *Skip to Results*.

* *Guided Search*:
Guided Search is enabled when you select a solution. The  guided search provides a guided workflow to refine a criteria further.

==== Steps
1. Click *Solution search* from the home page.
2. Select the view you want to use:
a. Click *Expert view* to see advanced criteria options.
b. Click *Guided view* to see simplified and guided criteria options.
3. In *Novice view*, select the search criteria options as they display:
a. Click *Skip* to move to the next component without making a selection. You can return to
the component by clicking *Unskip* as needed.
b. After the first five selections, click *Show More* to continue refining your search criteria.
+
You can return to the previous view by clicking *Show Less*.
+
c. When done, click *View Results* to see the supported configurations for your search criteria.
4. In *Expert view*, select the search criteria you want to use for the various components. We
recommend you move from left to right as each selection will refine the remaining criteria.
+
You do not have to make a selection for each component.
+
a. When done, click *View Results* to see the supported configurations for your search criteria.
5. You can also do the following as part of *Solution Search*:
a. Click the book icon to view the policy and guidelines applicable to your selection.
b. Click the chain icon to generate a sharable URL for your selections that you can share with
others.
c. Select the undo icon to clear all of you selections and start again.
6. From the results screen, you can do the following:
a. View the details, alerts, and information notices about your configuration.
b. Click the star icon to make this search a favorite. Name and describe the configuration. This becomes a saved search, viewable from the Saved Search menu. You can also subscribe to
the configuration here, which will notify you when changes are made. If you subscribe, you
will also see this listed under the Subscriptions menu.
c. Hover over the *Build End to End View With* to find additional supported solutions.
d. Click *What if* to change components and explore other compatibility options.

== Working with list and find
In the *List and Find* component work area you can view the best possible configurations for your components.

=== About this task
Use the *Component Explorer* panel on the left to view configurations for selected components. The panel on the right displays the solutions; each tab represents a storage solution and the number of configurations that use the selected components. If the green *Logic* toggle button on the *List and Find Component Workarea* is set to OR, you can search for solutions that have configurations containing single components. If the green *Logic* toggle button is set to AND, you can search for solutions that have configurations containing all the selected components. If multiple components are selected within the same component type, the button is set to OR.

=== Steps
1. Click *List and Find* on the home page.
2. Search for a component name in the *Component Explorer* or expand the selection to add components to the *List and Find Component Workarea*.

NOTE: You can select specific enabled solutions after adding a component to the *List and Find Component Workarea* before clicking *Next*. You can also export a maximum of 3000 rows for one solution at a time in an Excel spreadsheet or PDF.

3. Click *Next* to view where the components are used in configurations across multiple solutions on the *Results* page.
+
The most compatible configuration for your list of components is displayed.

=== Working with Advanced Search
You can search for different components using *Advanced Search* and add or remove components from your search criteria. You can use the search text box within the *Advanced Search* window to search for components. You can use the following filters as needed:

* Select *Do not show Limited Support components* to prevent seeing components with limited
support in the results.
* Select *Do not show EOVS components* to prevent seeing components with end-of-version
support in the results.

From this page, you can also view the *Component Explorer, Load saved criteria or configurations*, or use the *Search Assistant*.
