---
sidebar: sidebar
permalink: subscribing-to-config.html
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Solutions, Active IQ, Interop, Advisor, tool
summary:  'You can subscribe to configurations with any name of your choice for a particular solution or component.'
---

= Subscribe to configurations
:icons: font
:imagesdir: ./media/

[.lead]
You can subscribe to configurations with any name of your choice for a particular solution or component. This helps you to receive updates by email when there is an update or change in the subscribed row. You can subscribe to a maximum of 20 configurations.

== About this task
You can receive the emails for the following instances:

* When components are added to the configuration
* When components are deleted from the configuration
* When notes are added or deleted from the configuration
* When the state of the configuration is changed from supported to any of the additional terminal states – (EOS, Obsolete, and so on.)

== Steps
. In the *Results* page, click star to save the configuration.
After you save the configuration, the star turns yellow. You can save a maximum of 20
configurations.
. In the *Tag Configuration* dialog box, enter the name and description to bookmark the
configuration for reference.
. Click *Subscribe* to this configuration checkbox.
. Click *Tag*.
