---
sidebar: sidebar
permalink: working-with-ontap-san-host-solutions-search.html
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network
summary:  'Check compatibility for ONTAP version and Flash or Fabric storage version combinations. You can further refine your compatibility search for each relevant components'
---

= Work with ONTAP SAN Host Simplified search
:icons: font
:imagesdir: ./media/

[.lead]
Check the compatibility for ONTAP version and Flash or Fabric storage version combinations. You can further refine your compatibility search for each relevant components.

== About this task
You can check the compatibility between your Flash or Fabric storage devices on your SAN with the ONTAP version you want to use and other relevant components. You can choose between *Expert view* or *Novice view*.

NOTE: Click the *Set as default* option to automatically open a *ONTAP SAN Host Simplified* search whenever you open the IMT.

== Steps
. Click *ONTAP SAN Host Simplified* from the home page.
. Select the view you want to use:
.. Click *Expert view* to see advanced criteria options.
.. Click *Guided view* to see simplified and guided criteria options.
. In *Novice view*, select the search criteria options as they display.
.. Click *Skip* to move to the next component without making a selection. You can return to the component by clicking *Unskip* as needed.
.. After the first five selections, click *Show More* to continue refining your search criteria.
.. When done, click *View Results* to see the supported configurations for your search criteria.
. In *Expert view*, select the search criteria you want to use for the various components. We recommend you move from left to right as each selection will refine the remaining criteria. You do not have to make a selection for each component.
.. When done, click *View Results* to see the supported configurations for your search criteria.
. You can also do the following as part of the *ONTAP SAN Host Simplified*:
.. Click the book icon to view the policy and guidelines applicable to your selection.
.. Click the chain icon to generate a sharable URL for your selections that you can share with others.
.. Select the undo icon to clear all of your selections and start again.
. From the results screen, you can do the following:
.. View the details, alerts, and information notices about your configuration.
.. Click the star icon to make this search a favorite. Name and describe the configuration. This becomes a saved search, viewable from the *Saved Search* menu. You can also subscribe to the configuration here, which will notify you when changes are made. If you subscribe, you will also see this listed under the *Subscriptions* menu.
.. Hover over the *Build End to End View With* to find additional supported solutions.
.. Click *What if* to change components and explore other compatibility options.
